<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240313110848 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ct_autre_donne (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, attribut VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ct_type_imprime (id INT AUTO_INCREMENT NOT NULL, tit_libelle VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE ct_user DROP FOREIGN KEY FK_A115979E1B557D75');
        $this->addSql('ALTER TABLE ct_user DROP FOREIGN KEY FK_A115979E36C2F638');
        $this->addSql('ALTER TABLE ct_const_av_ded DROP FOREIGN KEY FK_5116CBDE4B6E02');
        $this->addSql('ALTER TABLE ct_const_av_ded DROP FOREIGN KEY FK_5116CBDE85C06CB');
        $this->addSql('ALTER TABLE ct_const_av_ded DROP FOREIGN KEY FK_5116CBD36C2F638');
        $this->addSql('ALTER TABLE ct_genre_tarif DROP FOREIGN KEY FK_CD5527BABC603024');
        $this->addSql('ALTER TABLE ct_vehicule DROP FOREIGN KEY FK_BCF5CAE412EA7B94');
        $this->addSql('ALTER TABLE ct_vehicule DROP FOREIGN KEY FK_BCF5CAE4BC603024');
        $this->addSql('ALTER TABLE ct_anomalie DROP FOREIGN KEY FK_E48094659A0FD0E5');
        $this->addSql('ALTER TABLE ct_arrete_prix DROP FOREIGN KEY FK_1CEB5E02E4B6E02');
        $this->addSql('ALTER TABLE ct_imprime_tech_use DROP FOREIGN KEY FK_ACFCEC1CB1D04D41');
        $this->addSql('ALTER TABLE ct_imprime_tech_use DROP FOREIGN KEY FK_ACFCEC1C36C2F638');
        $this->addSql('ALTER TABLE ct_imprime_tech_use DROP FOREIGN KEY FK_ACFCEC1CD930EA7D');
        $this->addSql('ALTER TABLE ct_imprime_tech_use DROP FOREIGN KEY FK_ACFCEC1C922496EB');
        $this->addSql('ALTER TABLE ct_imprime_tech_use DROP FOREIGN KEY FK_ACFCEC1CE4B6E02');
        $this->addSql('ALTER TABLE ct_usage_tarif DROP FOREIGN KEY FK_FA9D5B81F18C25C4');
        $this->addSql('ALTER TABLE ct_usage_tarif DROP FOREIGN KEY FK_FA9D5B812BD53E47');
        $this->addSql('ALTER TABLE ct_usage_tarif DROP FOREIGN KEY FK_FA9D5B818BA84C1F');
        $this->addSql('ALTER TABLE ct_const_av_ded_ct_const_av_ded_carac DROP FOREIGN KEY FK_DF8A0DAB83FAC2F');
        $this->addSql('ALTER TABLE ct_const_av_ded_ct_const_av_ded_carac DROP FOREIGN KEY FK_DF8A0DABC567580F');
        $this->addSql('ALTER TABLE ct_visite DROP FOREIGN KEY FK_7F3E82E336C2F638');
        $this->addSql('ALTER TABLE ct_visite DROP FOREIGN KEY FK_7F3E82E3E4B6E02');
        $this->addSql('ALTER TABLE ct_visite DROP FOREIGN KEY FK_7F3E82E3F8F2EE9');
        $this->addSql('ALTER TABLE ct_visite DROP FOREIGN KEY FK_7F3E82E38BA84C1F');
        $this->addSql('ALTER TABLE ct_visite DROP FOREIGN KEY FK_7F3E82E3E85C06CB');
        $this->addSql('ALTER TABLE ct_visite DROP FOREIGN KEY FK_7F3E82E3A7D01DE7');
        $this->addSql('ALTER TABLE ct_visite DROP FOREIGN KEY FK_7F3E82E3F18C25C4');
        $this->addSql('ALTER TABLE ct_motif_tarif DROP FOREIGN KEY FK_110F10F8603A0766');
        $this->addSql('ALTER TABLE ct_motif_tarif DROP FOREIGN KEY FK_110F10F876255A68');
        $this->addSql('ALTER TABLE ct_visite_ct_visite_extra DROP FOREIGN KEY FK_F9CF011A15D88434');
        $this->addSql('ALTER TABLE ct_visite_ct_visite_extra DROP FOREIGN KEY FK_F9CF011A5314CD4');
        $this->addSql('ALTER TABLE ct_visite_extra_tarif DROP FOREIGN KEY FK_E3F1985EB1D04D41');
        $this->addSql('ALTER TABLE ct_visite_extra_tarif DROP FOREIGN KEY FK_E3F1985E2BD53E47');
        $this->addSql('ALTER TABLE ct_genre DROP FOREIGN KEY FK_9BCBF2CE3BEDFDD8');
        $this->addSql('ALTER TABLE ct_extra_vente DROP FOREIGN KEY FK_C33DB5AE1D358EA');
        $this->addSql('ALTER TABLE ct_extra_vente DROP FOREIGN KEY FK_C33DB5A92C48FC0');
        $this->addSql('ALTER TABLE ct_carte_grise DROP FOREIGN KEY FK_A447BE7336C2F638');
        $this->addSql('ALTER TABLE ct_carte_grise DROP FOREIGN KEY FK_A447BE73C89A4997');
        $this->addSql('ALTER TABLE ct_carte_grise DROP FOREIGN KEY FK_A447BE7311BAA3BA');
        $this->addSql('ALTER TABLE ct_carte_grise DROP FOREIGN KEY FK_A447BE73A6F03AC4');
        $this->addSql('ALTER TABLE ct_carte_grise DROP FOREIGN KEY FK_A447BE73E4B6E02');
        $this->addSql('ALTER TABLE ct_carte_grise DROP FOREIGN KEY FK_A447BE73347AECB7');
        $this->addSql('ALTER TABLE ct_carte_grise DROP FOREIGN KEY FK_A447BE73A7D01DE7');
        $this->addSql('ALTER TABLE ct_carte_grise DROP FOREIGN KEY FK_A447BE73E926E299');
        $this->addSql('ALTER TABLE ct_reception DROP FOREIGN KEY FK_942215A2BC603024');
        $this->addSql('ALTER TABLE ct_reception DROP FOREIGN KEY FK_942215A2E85C06CB');
        $this->addSql('ALTER TABLE ct_reception DROP FOREIGN KEY FK_942215A236C2F638');
        $this->addSql('ALTER TABLE ct_reception DROP FOREIGN KEY FK_942215A2A7D01DE7');
        $this->addSql('ALTER TABLE ct_reception DROP FOREIGN KEY FK_942215A2C89A4997');
        $this->addSql('ALTER TABLE ct_reception DROP FOREIGN KEY FK_942215A2E926E299');
        $this->addSql('ALTER TABLE ct_reception DROP FOREIGN KEY FK_942215A2603A0766');
        $this->addSql('ALTER TABLE ct_reception DROP FOREIGN KEY FK_942215A2AA1F8D61');
        $this->addSql('ALTER TABLE ct_reception DROP FOREIGN KEY FK_942215A2E4B6E02');
        $this->addSql('ALTER TABLE ct_reception DROP FOREIGN KEY FK_942215A2A6F03AC4');
        $this->addSql('ALTER TABLE ct_proces_verbal DROP FOREIGN KEY FK_556CD10D2BD53E47');
        $this->addSql('ALTER TABLE ct_centre DROP FOREIGN KEY FK_902E42D3E4756BB');
        $this->addSql('ALTER TABLE ct_centre DROP FOREIGN KEY FK_902E42D71BF4F4B');
        $this->addSql('ALTER TABLE ct_photo DROP FOREIGN KEY FK_C2C452EDBB11B80');
        $this->addSql('ALTER TABLE ct_historique DROP FOREIGN KEY FK_7E72DEE1D2EF42B4');
        $this->addSql('ALTER TABLE ct_historique DROP FOREIGN KEY FK_7E72DEE1E2C56C4A');
        $this->addSql('ALTER TABLE ct_historique DROP FOREIGN KEY FK_7E72DEE1E4B6E02');
        $this->addSql('ALTER TABLE ct_imprime_tech DROP FOREIGN KEY FK_3F49AE42E4B6E02');
        $this->addSql('ALTER TABLE ct_usage DROP FOREIGN KEY FK_C8709F46EAF3885');
        $this->addSql('ALTER TABLE ct_autre_vente DROP FOREIGN KEY FK_BD5B077B3A162080');
        $this->addSql('ALTER TABLE ct_autre_vente DROP FOREIGN KEY FK_BD5B077BDBB11B80');
        $this->addSql('ALTER TABLE ct_autre_vente DROP FOREIGN KEY FK_BD5B077B4A8E174A');
        $this->addSql('ALTER TABLE ct_autre_vente DROP FOREIGN KEY FK_BD5B077BF8F2EE9');
        $this->addSql('ALTER TABLE ct_autre_vente DROP FOREIGN KEY FK_BD5B077B36C2F638');
        $this->addSql('ALTER TABLE ct_autre_vente DROP FOREIGN KEY FK_BD5B077B9D86650F');
        $this->addSql('ALTER TABLE ct_bordereau DROP FOREIGN KEY FK_334055ECB1D04D41');
        $this->addSql('ALTER TABLE ct_bordereau DROP FOREIGN KEY FK_334055ECE4B6E02');
        $this->addSql('ALTER TABLE ct_bordereau DROP FOREIGN KEY FK_334055EC36C2F638');
        $this->addSql('ALTER TABLE ct_visite_ct_anomalie DROP FOREIGN KEY FK_F39BC552D0C80021');
        $this->addSql('ALTER TABLE ct_visite_ct_anomalie DROP FOREIGN KEY FK_F39BC5525314CD4');
        $this->addSql('ALTER TABLE ct_autre_vente_ct_visite_extra DROP FOREIGN KEY FK_38C3E3BC15D88434');
        $this->addSql('ALTER TABLE ct_autre_vente_ct_visite_extra DROP FOREIGN KEY FK_38C3E3BC8D1D5C87');
        $this->addSql('ALTER TABLE ct_droit_ptac DROP FOREIGN KEY FK_DB918ADA2BD53E47');
        $this->addSql('ALTER TABLE ct_droit_ptac DROP FOREIGN KEY FK_DB918ADA3BEDFDD8');
        $this->addSql('ALTER TABLE ct_droit_ptac DROP FOREIGN KEY FK_DB918ADA5FFCB50');
        $this->addSql('ALTER TABLE ct_autre_tarif DROP FOREIGN KEY FK_3BA0A4FE32BBA609');
        $this->addSql('ALTER TABLE ct_const_av_ded_carac DROP FOREIGN KEY FK_FAC238B6BC603024');
        $this->addSql('ALTER TABLE ct_const_av_ded_carac DROP FOREIGN KEY FK_FAC238B6E926E299');
        $this->addSql('ALTER TABLE ct_const_av_ded_carac DROP FOREIGN KEY FK_FAC238B6BE9C66F4');
        $this->addSql('ALTER TABLE ct_const_av_ded_carac DROP FOREIGN KEY FK_FAC238B612EA7B94');
        $this->addSql('ALTER TABLE ct_const_av_ded_carac DROP FOREIGN KEY FK_FAC238B6C89A4997');
        $this->addSql('DROP TABLE ct_type_droit_ptac');
        $this->addSql('DROP TABLE ct_carrosserie');
        $this->addSql('DROP TABLE ct_user');
        $this->addSql('DROP TABLE ct_const_av_ded');
        $this->addSql('DROP TABLE ct_genre_tarif');
        $this->addSql('DROP TABLE ct_motif');
        $this->addSql('DROP TABLE ct_vehicule');
        $this->addSql('DROP TABLE ct_anomalie');
        $this->addSql('DROP TABLE ct_arrete_prix');
        $this->addSql('DROP TABLE ct_imprime_tech_use');
        $this->addSql('DROP TABLE ct_province');
        $this->addSql('DROP TABLE ct_usage_tarif');
        $this->addSql('DROP TABLE ct_type_reception');
        $this->addSql('DROP TABLE ct_const_av_ded_ct_const_av_ded_carac');
        $this->addSql('DROP TABLE ct_visite');
        $this->addSql('DROP TABLE ct_type_usage');
        $this->addSql('DROP TABLE ct_motif_tarif');
        $this->addSql('DROP TABLE ct_zone_desserte');
        $this->addSql('DROP TABLE ct_visite_ct_visite_extra');
        $this->addSql('DROP TABLE ct_visite_extra_tarif');
        $this->addSql('DROP TABLE ct_genre');
        $this->addSql('DROP TABLE ct_extra_vente');
        $this->addSql('DROP TABLE ct_marque');
        $this->addSql('DROP TABLE ct_carte_grise');
        $this->addSql('DROP TABLE ct_source_energie');
        $this->addSql('DROP TABLE ct_reception');
        $this->addSql('DROP TABLE ct_proces_verbal');
        $this->addSql('DROP TABLE ct_centre');
        $this->addSql('DROP TABLE ct_photo');
        $this->addSql('DROP TABLE ct_const_av_ded_type');
        $this->addSql('DROP TABLE ct_historique');
        $this->addSql('DROP TABLE ct_imprime_tech');
        $this->addSql('DROP TABLE ct_anomalie_type');
        $this->addSql('DROP TABLE ct_autre');
        $this->addSql('DROP TABLE ct_usage');
        $this->addSql('DROP TABLE ct_autre_vente');
        $this->addSql('DROP TABLE ct_genre_categorie');
        $this->addSql('DROP TABLE ct_role');
        $this->addSql('DROP TABLE ct_type_visite');
        $this->addSql('DROP TABLE ct_bordereau');
        $this->addSql('DROP TABLE ct_visite_extra');
        $this->addSql('DROP TABLE ct_usage_imprime_technique');
        $this->addSql('DROP TABLE ct_visite_ct_anomalie');
        $this->addSql('DROP TABLE ct_utilisation');
        $this->addSql('DROP TABLE ct_autre_vente_ct_visite_extra');
        $this->addSql('DROP TABLE ct_droit_ptac');
        $this->addSql('DROP TABLE ct_autre_tarif');
        $this->addSql('DROP TABLE ct_historique_type');
        $this->addSql('DROP TABLE ct_const_av_ded_carac');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ct_type_droit_ptac (id INT AUTO_INCREMENT NOT NULL, tp_dp_libelle VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_carrosserie (id INT AUTO_INCREMENT NOT NULL, crs_libelle VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_user (id INT AUTO_INCREMENT NOT NULL, ct_centre_id_id INT DEFAULT NULL, ct_role_id_id INT DEFAULT NULL, username VARCHAR(180) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, roles JSON NOT NULL COMMENT \'(DC2Type:json)\', password VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, usr_enable TINYINT(1) NOT NULL, usr_last_login DATETIME DEFAULT NULL, usr_mail VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, usr_nom VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, usr_adresse VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, usr_created_at DATETIME DEFAULT NULL, usr_updated_at DATETIME DEFAULT NULL, usr_telephone VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, usr_nbr_connexion INT DEFAULT NULL, UNIQUE INDEX UNIQ_A115979EF85E0677 (username), INDEX IDX_A115979E36C2F638 (ct_centre_id_id), INDEX IDX_A115979E1B557D75 (ct_role_id_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_const_av_ded (id INT AUTO_INCREMENT NOT NULL, ct_centre_id_id INT DEFAULT NULL, ct_verificateur_id_id INT DEFAULT NULL, ct_user_id_id INT DEFAULT NULL, cad_provenance VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, cad_divers VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, cad_proprietaire_nom VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, cad_proprietaire_adresse VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, cad_bon_etat TINYINT(1) NOT NULL, cad_sec_pers TINYINT(1) NOT NULL, cad_sec_march TINYINT(1) NOT NULL, cad_protec_env TINYINT(1) NOT NULL, cad_numero VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, cad_immatriculation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, cad_date_embarquement DATE DEFAULT NULL, cad_lieu_embarquement VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, cad_created DATETIME NOT NULL, cad_observation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, cad_conforme TINYINT(1) NOT NULL, cad_is_active TINYINT(1) NOT NULL, cad_genere INT NOT NULL, INDEX IDX_5116CBDE4B6E02 (ct_user_id_id), INDEX IDX_5116CBD36C2F638 (ct_centre_id_id), INDEX IDX_5116CBDE85C06CB (ct_verificateur_id_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_genre_tarif (id INT AUTO_INCREMENT NOT NULL, ct_genre_id_id INT NOT NULL, grt_prix DOUBLE PRECISION NOT NULL, grt_annee DATE NOT NULL, INDEX IDX_CD5527BABC603024 (ct_genre_id_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_motif (id INT AUTO_INCREMENT NOT NULL, mtf_libelle VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, mtf_is_calculable TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_vehicule (id INT AUTO_INCREMENT NOT NULL, ct_genre_id_id INT DEFAULT NULL, ct_marque_id_id INT DEFAULT NULL, vhc_cylindre DOUBLE PRECISION DEFAULT NULL, vhc_puissance DOUBLE PRECISION DEFAULT NULL, vhc_poids_vide DOUBLE PRECISION DEFAULT NULL, vhc_charge_utile DOUBLE PRECISION DEFAULT NULL, vhc_hauteur DOUBLE PRECISION DEFAULT NULL, vhc_largeur DOUBLE PRECISION DEFAULT NULL, vhc_longueur DOUBLE PRECISION DEFAULT NULL, vhc_num_serie VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, vhc_num_moteur VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, vhc_created DATETIME NOT NULL, vhc_provenance VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, vhc_type VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, vhc_poids_total_charge DOUBLE PRECISION DEFAULT NULL, INDEX IDX_BCF5CAE4BC603024 (ct_genre_id_id), INDEX IDX_BCF5CAE412EA7B94 (ct_marque_id_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_anomalie (id INT AUTO_INCREMENT NOT NULL, ct_anomalie_type_id_id INT NOT NULL, anml_libelle VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, anml_code VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, anml_niveau_danger INT DEFAULT NULL, INDEX IDX_E48094659A0FD0E5 (ct_anomalie_type_id_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_arrete_prix (id INT AUTO_INCREMENT NOT NULL, ct_user_id_id INT DEFAULT NULL, art_numero VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, art_date DATE DEFAULT NULL, art_date_application DATE DEFAULT NULL, art_created_at DATE NOT NULL, art_updated_at DATE DEFAULT NULL, art_observation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_1CEB5E02E4B6E02 (ct_user_id_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_imprime_tech_use (id INT AUTO_INCREMENT NOT NULL, ct_bordereau_id_id INT DEFAULT NULL, ct_centre_id_id INT DEFAULT NULL, ct_imprime_tech_id_id INT DEFAULT NULL, ct_user_id_id INT DEFAULT NULL, ct_usage_it_id_id INT DEFAULT NULL, ct_controle_id INT DEFAULT NULL, itu_numero INT DEFAULT NULL, itu_used TINYINT(1) NOT NULL, actived_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, itu_observation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, itu_is_visible TINYINT(1) NOT NULL, INDEX IDX_ACFCEC1C922496EB (ct_usage_it_id_id), INDEX IDX_ACFCEC1C36C2F638 (ct_centre_id_id), INDEX IDX_ACFCEC1CB1D04D41 (ct_imprime_tech_id_id), INDEX IDX_ACFCEC1CE4B6E02 (ct_user_id_id), INDEX IDX_ACFCEC1CD930EA7D (ct_bordereau_id_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_province (id INT AUTO_INCREMENT NOT NULL, prv_nom VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, prv_code VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, prv_created_at DATE NOT NULL, prv_updated_at DATE DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_usage_tarif (id INT AUTO_INCREMENT NOT NULL, ct_usage_id_id INT DEFAULT NULL, ct_type_visite_id_id INT DEFAULT NULL, ct_arrete_prix_id_id INT DEFAULT NULL, usg_trf_annee VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, usg_trf_prix DOUBLE PRECISION NOT NULL, INDEX IDX_FA9D5B818BA84C1F (ct_usage_id_id), INDEX IDX_FA9D5B81F18C25C4 (ct_type_visite_id_id), INDEX IDX_FA9D5B812BD53E47 (ct_arrete_prix_id_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_type_reception (id INT AUTO_INCREMENT NOT NULL, tprcp_libelle VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_const_av_ded_ct_const_av_ded_carac (ct_const_av_ded_id INT NOT NULL, ct_const_av_ded_carac_id INT NOT NULL, INDEX IDX_DF8A0DABC567580F (ct_const_av_ded_carac_id), INDEX IDX_DF8A0DAB83FAC2F (ct_const_av_ded_id), PRIMARY KEY(ct_const_av_ded_id, ct_const_av_ded_carac_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_visite (id INT AUTO_INCREMENT NOT NULL, ct_carte_grise_id_id INT DEFAULT NULL, ct_centre_id_id INT DEFAULT NULL, ct_type_visite_id_id INT DEFAULT NULL, ct_usage_id_id INT DEFAULT NULL, ct_user_id_id INT DEFAULT NULL, ct_verificateur_id_id INT DEFAULT NULL, ct_utilisation_id_id INT DEFAULT NULL, vst_num_pv VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, vst_num_feuille_caisse VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, vst_date_expiration DATE DEFAULT NULL, vst_created DATETIME DEFAULT NULL, vst_updated DATETIME DEFAULT NULL, vst_is_apte TINYINT(1) NOT NULL, vst_is_contre_visite TINYINT(1) NOT NULL, vst_duree_reparation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, vst_is_active TINYINT(1) NOT NULL, vst_genere INT DEFAULT NULL, vst_observation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_7F3E82E3E4B6E02 (ct_user_id_id), INDEX IDX_7F3E82E336C2F638 (ct_centre_id_id), INDEX IDX_7F3E82E3E85C06CB (ct_verificateur_id_id), INDEX IDX_7F3E82E3F18C25C4 (ct_type_visite_id_id), INDEX IDX_7F3E82E3A7D01DE7 (ct_utilisation_id_id), INDEX IDX_7F3E82E38BA84C1F (ct_usage_id_id), INDEX IDX_7F3E82E3F8F2EE9 (ct_carte_grise_id_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_type_usage (id INT AUTO_INCREMENT NOT NULL, tpu_libelle VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_motif_tarif (id INT AUTO_INCREMENT NOT NULL, ct_motif_id_id INT DEFAULT NULL, ct_arrete_prix_id INT DEFAULT NULL, mtf_trf_prix DOUBLE PRECISION NOT NULL, mtf_trf_date DATE NOT NULL, INDEX IDX_110F10F8603A0766 (ct_motif_id_id), INDEX IDX_110F10F876255A68 (ct_arrete_prix_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_zone_desserte (id INT AUTO_INCREMENT NOT NULL, zd_libelle VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_visite_ct_visite_extra (ct_visite_id INT NOT NULL, ct_visite_extra_id INT NOT NULL, INDEX IDX_F9CF011A5314CD4 (ct_visite_id), INDEX IDX_F9CF011A15D88434 (ct_visite_extra_id), PRIMARY KEY(ct_visite_id, ct_visite_extra_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_visite_extra_tarif (id INT AUTO_INCREMENT NOT NULL, ct_imprime_tech_id_id INT DEFAULT NULL, ct_arrete_prix_id_id INT DEFAULT NULL, vet_annee VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, vet_prix DOUBLE PRECISION NOT NULL, INDEX IDX_E3F1985EB1D04D41 (ct_imprime_tech_id_id), INDEX IDX_E3F1985E2BD53E47 (ct_arrete_prix_id_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_genre (id INT AUTO_INCREMENT NOT NULL, ct_genre_categorie_id_id INT DEFAULT NULL, gr_libelle VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, gr_code VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_9BCBF2CE3BEDFDD8 (ct_genre_categorie_id_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_extra_vente (id INT AUTO_INCREMENT NOT NULL, ct_visite_id_id INT DEFAULT NULL, ct_visite_extra_id_id INT DEFAULT NULL, exv_created_at DATETIME DEFAULT NULL, exv_is_active TINYINT(1) NOT NULL, INDEX IDX_C33DB5A92C48FC0 (ct_visite_extra_id_id), INDEX IDX_C33DB5AE1D358EA (ct_visite_id_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_marque (id INT AUTO_INCREMENT NOT NULL, mrq_libelle VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_carte_grise (id INT AUTO_INCREMENT NOT NULL, ct_carrosserie_id_id INT DEFAULT NULL, ct_centre_id_id INT DEFAULT NULL, ct_source_energie_id_id INT DEFAULT NULL, ct_vehicule_id_id INT DEFAULT NULL, ct_user_id_id INT DEFAULT NULL, ct_zone_desserte_id_id INT DEFAULT NULL, cg_antecedant_id_id INT DEFAULT NULL, ct_utilisation_id_id INT DEFAULT NULL, cg_date_emission DATE DEFAULT NULL, cg_nom VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, cg_prenom VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, cg_profession VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, cg_adresse VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, cg_phone VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, cg_nbr_assis INT NOT NULL, cg_nbr_debout INT NOT NULL, cg_puissance_admin INT NOT NULL, cg_mise_en_service DATE DEFAULT NULL, cg_patente VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, cg_ani VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, cg_rta VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, cg_num_carte_violette VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, cg_date_carte_violette DATE DEFAULT NULL, cg_lieu_carte_violette VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, cg_num_vignette VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, cg_date_vignette DATE DEFAULT NULL, cg_lieu_vignette VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, cg_immatriculation VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, cg_created DATETIME NOT NULL, cg_nom_cooperative VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, cg_itineraire VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, cg_is_transport TINYINT(1) NOT NULL, cg_num_identification VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, cg_is_active TINYINT(1) NOT NULL, cg_observation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, cg_commune VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_A447BE73A7D01DE7 (ct_utilisation_id_id), INDEX IDX_A447BE73E4B6E02 (ct_user_id_id), INDEX IDX_A447BE7336C2F638 (ct_centre_id_id), INDEX IDX_A447BE7311BAA3BA (ct_zone_desserte_id_id), INDEX IDX_A447BE73E926E299 (ct_source_energie_id_id), INDEX IDX_A447BE73347AECB7 (cg_antecedant_id_id), INDEX IDX_A447BE73A6F03AC4 (ct_vehicule_id_id), INDEX IDX_A447BE73C89A4997 (ct_carrosserie_id_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_source_energie (id INT AUTO_INCREMENT NOT NULL, sre_libelle VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_reception (id INT AUTO_INCREMENT NOT NULL, ct_centre_id_id INT DEFAULT NULL, ct_motif_id_id INT DEFAULT NULL, ct_type_reception_id_id INT DEFAULT NULL, ct_user_id_id INT DEFAULT NULL, ct_verificateur_id_id INT DEFAULT NULL, ct_utilisation_id_id INT DEFAULT NULL, ct_vehicule_id_id INT DEFAULT NULL, ct_source_energie_id_id INT DEFAULT NULL, ct_carrosserie_id_id INT DEFAULT NULL, ct_genre_id_id INT DEFAULT NULL, rcp_mise_service DATE DEFAULT NULL, rcp_immatriculation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, rcp_proprietaire VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, rcp_profession VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, rcp_adresse VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, rcp_nbr_assis INT DEFAULT NULL, rcp_ngr_debout INT DEFAULT NULL, rcp_num_pv VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, rcp_num_group VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, rcp_created DATETIME DEFAULT NULL, rcp_is_active TINYINT(1) NOT NULL, rcp_genere INT NOT NULL, rcp_observation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_942215A2E4B6E02 (ct_user_id_id), INDEX IDX_942215A236C2F638 (ct_centre_id_id), INDEX IDX_942215A2E926E299 (ct_source_energie_id_id), INDEX IDX_942215A2E85C06CB (ct_verificateur_id_id), INDEX IDX_942215A2603A0766 (ct_motif_id_id), INDEX IDX_942215A2C89A4997 (ct_carrosserie_id_id), INDEX IDX_942215A2A7D01DE7 (ct_utilisation_id_id), INDEX IDX_942215A2AA1F8D61 (ct_type_reception_id_id), INDEX IDX_942215A2BC603024 (ct_genre_id_id), INDEX IDX_942215A2A6F03AC4 (ct_vehicule_id_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_proces_verbal (id INT AUTO_INCREMENT NOT NULL, ct_arrete_prix_id_id INT DEFAULT NULL, pv_type VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, pv_tarif DOUBLE PRECISION NOT NULL, INDEX IDX_556CD10D2BD53E47 (ct_arrete_prix_id_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_centre (id INT AUTO_INCREMENT NOT NULL, ct_province_id_id INT NOT NULL, centre_mere_id INT DEFAULT NULL, ctr_nom VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, ctr_code VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, ctr_created_at DATE NOT NULL, ctr_updated_at DATE DEFAULT NULL, INDEX IDX_902E42D3E4756BB (ct_province_id_id), INDEX IDX_902E42D71BF4F4B (centre_mere_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_photo (id INT AUTO_INCREMENT NOT NULL, ct_usage_it_id INT DEFAULT NULL, ct_controle_id INT DEFAULT NULL, pht_nom VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, pht_dossier VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_C2C452EDBB11B80 (ct_usage_it_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_const_av_ded_type (id INT AUTO_INCREMENT NOT NULL, cad_tp_libelle VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_historique (id INT AUTO_INCREMENT NOT NULL, ct_user_id_id INT NOT NULL, ct_center_id_id INT DEFAULT NULL, ct_historique_type_id_id INT DEFAULT NULL, hst_description VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, hst_date_created_at DATETIME NOT NULL, hst_is_view INT NOT NULL, INDEX IDX_7E72DEE1E4B6E02 (ct_user_id_id), INDEX IDX_7E72DEE1E2C56C4A (ct_center_id_id), INDEX IDX_7E72DEE1D2EF42B4 (ct_historique_type_id_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_imprime_tech (id INT AUTO_INCREMENT NOT NULL, ct_user_id_id INT DEFAULT NULL, nom_imprime_tech VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, ute_imprime_tech VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, abrev_imprime_tech VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, prtt_created_at DATE NOT NULL, prtt_updated_at DATE DEFAULT NULL, INDEX IDX_3F49AE42E4B6E02 (ct_user_id_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_anomalie_type (id INT AUTO_INCREMENT NOT NULL, atp_libelle VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_autre (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, attribut VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_usage (id INT AUTO_INCREMENT NOT NULL, ct_type_usage_id_id INT DEFAULT NULL, usg_libelle VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, usg_validite INT NOT NULL, usg_created DATE DEFAULT NULL, INDEX IDX_C8709F46EAF3885 (ct_type_usage_id_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_autre_vente (id INT AUTO_INCREMENT NOT NULL, ct_usage_it_id INT DEFAULT NULL, ct_autre_tarif_id_id INT DEFAULT NULL, user_id_id INT DEFAULT NULL, verificateur_id_id INT DEFAULT NULL, ct_carte_grise_id_id INT DEFAULT NULL, ct_centre_id_id INT DEFAULT NULL, auv_is_visible TINYINT(1) NOT NULL, auv_created_at DATETIME DEFAULT NULL, controle_id INT DEFAULT NULL, auv_validite VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, auv_itineraire VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, auv_num_pv VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_BD5B077B9D86650F (user_id_id), INDEX IDX_BD5B077B4A8E174A (verificateur_id_id), INDEX IDX_BD5B077BDBB11B80 (ct_usage_it_id), INDEX IDX_BD5B077BF8F2EE9 (ct_carte_grise_id_id), INDEX IDX_BD5B077B3A162080 (ct_autre_tarif_id_id), INDEX IDX_BD5B077B36C2F638 (ct_centre_id_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_genre_categorie (id INT AUTO_INCREMENT NOT NULL, gc_libelle VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, gc_is_calculable TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_role (id INT AUTO_INCREMENT NOT NULL, role_name VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_type_visite (id INT AUTO_INCREMENT NOT NULL, tpv_libelle VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_bordereau (id INT AUTO_INCREMENT NOT NULL, ct_centre_id_id INT DEFAULT NULL, ct_imprime_tech_id_id INT DEFAULT NULL, ct_user_id_id INT DEFAULT NULL, bl_numero VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, bl_debut_numero INT NOT NULL, bl_fin_numero INT NOT NULL, bl_created_at DATE NOT NULL, bl_updated_at DATE DEFAULT NULL, ref_expr VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, date_ref_expr DATE DEFAULT NULL, bl_observation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_334055ECE4B6E02 (ct_user_id_id), INDEX IDX_334055EC36C2F638 (ct_centre_id_id), INDEX IDX_334055ECB1D04D41 (ct_imprime_tech_id_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_visite_extra (id INT AUTO_INCREMENT NOT NULL, vste_libelle VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_usage_imprime_technique (id INT AUTO_INCREMENT NOT NULL, uit_libelle VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_visite_ct_anomalie (ct_visite_id INT NOT NULL, ct_anomalie_id INT NOT NULL, INDEX IDX_F39BC552D0C80021 (ct_anomalie_id), INDEX IDX_F39BC5525314CD4 (ct_visite_id), PRIMARY KEY(ct_visite_id, ct_anomalie_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_utilisation (id INT AUTO_INCREMENT NOT NULL, ut_libelle VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_autre_vente_ct_visite_extra (ct_autre_vente_id INT NOT NULL, ct_visite_extra_id INT NOT NULL, INDEX IDX_38C3E3BC8D1D5C87 (ct_autre_vente_id), INDEX IDX_38C3E3BC15D88434 (ct_visite_extra_id), PRIMARY KEY(ct_autre_vente_id, ct_visite_extra_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_droit_ptac (id INT AUTO_INCREMENT NOT NULL, ct_genre_categorie_id_id INT DEFAULT NULL, ct_type_droit_ptac_id_id INT DEFAULT NULL, ct_arrete_prix_id_id INT DEFAULT NULL, dp_prix_min DOUBLE PRECISION DEFAULT NULL, dp_prix_max DOUBLE PRECISION DEFAULT NULL, dp_droit DOUBLE PRECISION NOT NULL, INDEX IDX_DB918ADA2BD53E47 (ct_arrete_prix_id_id), INDEX IDX_DB918ADA3BEDFDD8 (ct_genre_categorie_id_id), INDEX IDX_DB918ADA5FFCB50 (ct_type_droit_ptac_id_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_autre_tarif (id INT AUTO_INCREMENT NOT NULL, ct_usage_imprime_technique_id_id INT NOT NULL, aut_prix DOUBLE PRECISION NOT NULL, aut_arrete VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, aut_date DATE DEFAULT NULL, INDEX IDX_3BA0A4FE32BBA609 (ct_usage_imprime_technique_id_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_historique_type (id INT AUTO_INCREMENT NOT NULL, hst_libelle VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE ct_const_av_ded_carac (id INT AUTO_INCREMENT NOT NULL, ct_carrosserie_id_id INT DEFAULT NULL, ct_const_av_ded_type_id_id INT DEFAULT NULL, ct_genre_id_id INT DEFAULT NULL, ct_marque_id_id INT DEFAULT NULL, ct_source_energie_id_id INT DEFAULT NULL, cad_cylindre DOUBLE PRECISION DEFAULT NULL, cad_puissance DOUBLE PRECISION DEFAULT NULL, cad_poids_vide DOUBLE PRECISION DEFAULT NULL, cad_charge_utile DOUBLE PRECISION DEFAULT NULL, cad_hauteur DOUBLE PRECISION DEFAULT NULL, cad_largeur DOUBLE PRECISION DEFAULT NULL, cad_longueur DOUBLE PRECISION DEFAULT NULL, cad_num_serie_type VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, cad_num_moteur VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, cad_type_car VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, cad_poids_maxima LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, cad_poids_total_charge DOUBLE PRECISION DEFAULT NULL, cad_premiere_circule VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, cad_nbr_assis INT DEFAULT NULL, INDEX IDX_FAC238B6BE9C66F4 (ct_const_av_ded_type_id_id), INDEX IDX_FAC238B6BC603024 (ct_genre_id_id), INDEX IDX_FAC238B612EA7B94 (ct_marque_id_id), INDEX IDX_FAC238B6C89A4997 (ct_carrosserie_id_id), INDEX IDX_FAC238B6E926E299 (ct_source_energie_id_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE ct_user ADD CONSTRAINT FK_A115979E1B557D75 FOREIGN KEY (ct_role_id_id) REFERENCES ct_role (id)');
        $this->addSql('ALTER TABLE ct_user ADD CONSTRAINT FK_A115979E36C2F638 FOREIGN KEY (ct_centre_id_id) REFERENCES ct_centre (id)');
        $this->addSql('ALTER TABLE ct_const_av_ded ADD CONSTRAINT FK_5116CBDE4B6E02 FOREIGN KEY (ct_user_id_id) REFERENCES ct_user (id)');
        $this->addSql('ALTER TABLE ct_const_av_ded ADD CONSTRAINT FK_5116CBDE85C06CB FOREIGN KEY (ct_verificateur_id_id) REFERENCES ct_user (id)');
        $this->addSql('ALTER TABLE ct_const_av_ded ADD CONSTRAINT FK_5116CBD36C2F638 FOREIGN KEY (ct_centre_id_id) REFERENCES ct_centre (id)');
        $this->addSql('ALTER TABLE ct_genre_tarif ADD CONSTRAINT FK_CD5527BABC603024 FOREIGN KEY (ct_genre_id_id) REFERENCES ct_genre (id)');
        $this->addSql('ALTER TABLE ct_vehicule ADD CONSTRAINT FK_BCF5CAE412EA7B94 FOREIGN KEY (ct_marque_id_id) REFERENCES ct_marque (id)');
        $this->addSql('ALTER TABLE ct_vehicule ADD CONSTRAINT FK_BCF5CAE4BC603024 FOREIGN KEY (ct_genre_id_id) REFERENCES ct_genre (id)');
        $this->addSql('ALTER TABLE ct_anomalie ADD CONSTRAINT FK_E48094659A0FD0E5 FOREIGN KEY (ct_anomalie_type_id_id) REFERENCES ct_anomalie_type (id)');
        $this->addSql('ALTER TABLE ct_arrete_prix ADD CONSTRAINT FK_1CEB5E02E4B6E02 FOREIGN KEY (ct_user_id_id) REFERENCES ct_user (id)');
        $this->addSql('ALTER TABLE ct_imprime_tech_use ADD CONSTRAINT FK_ACFCEC1CB1D04D41 FOREIGN KEY (ct_imprime_tech_id_id) REFERENCES ct_imprime_tech (id)');
        $this->addSql('ALTER TABLE ct_imprime_tech_use ADD CONSTRAINT FK_ACFCEC1C36C2F638 FOREIGN KEY (ct_centre_id_id) REFERENCES ct_centre (id)');
        $this->addSql('ALTER TABLE ct_imprime_tech_use ADD CONSTRAINT FK_ACFCEC1CD930EA7D FOREIGN KEY (ct_bordereau_id_id) REFERENCES ct_bordereau (id)');
        $this->addSql('ALTER TABLE ct_imprime_tech_use ADD CONSTRAINT FK_ACFCEC1C922496EB FOREIGN KEY (ct_usage_it_id_id) REFERENCES ct_usage_imprime_technique (id)');
        $this->addSql('ALTER TABLE ct_imprime_tech_use ADD CONSTRAINT FK_ACFCEC1CE4B6E02 FOREIGN KEY (ct_user_id_id) REFERENCES ct_user (id)');
        $this->addSql('ALTER TABLE ct_usage_tarif ADD CONSTRAINT FK_FA9D5B81F18C25C4 FOREIGN KEY (ct_type_visite_id_id) REFERENCES ct_type_visite (id)');
        $this->addSql('ALTER TABLE ct_usage_tarif ADD CONSTRAINT FK_FA9D5B812BD53E47 FOREIGN KEY (ct_arrete_prix_id_id) REFERENCES ct_arrete_prix (id)');
        $this->addSql('ALTER TABLE ct_usage_tarif ADD CONSTRAINT FK_FA9D5B818BA84C1F FOREIGN KEY (ct_usage_id_id) REFERENCES ct_usage (id)');
        $this->addSql('ALTER TABLE ct_const_av_ded_ct_const_av_ded_carac ADD CONSTRAINT FK_DF8A0DAB83FAC2F FOREIGN KEY (ct_const_av_ded_id) REFERENCES ct_const_av_ded (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ct_const_av_ded_ct_const_av_ded_carac ADD CONSTRAINT FK_DF8A0DABC567580F FOREIGN KEY (ct_const_av_ded_carac_id) REFERENCES ct_const_av_ded_carac (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ct_visite ADD CONSTRAINT FK_7F3E82E336C2F638 FOREIGN KEY (ct_centre_id_id) REFERENCES ct_centre (id)');
        $this->addSql('ALTER TABLE ct_visite ADD CONSTRAINT FK_7F3E82E3E4B6E02 FOREIGN KEY (ct_user_id_id) REFERENCES ct_user (id)');
        $this->addSql('ALTER TABLE ct_visite ADD CONSTRAINT FK_7F3E82E3F8F2EE9 FOREIGN KEY (ct_carte_grise_id_id) REFERENCES ct_carte_grise (id)');
        $this->addSql('ALTER TABLE ct_visite ADD CONSTRAINT FK_7F3E82E38BA84C1F FOREIGN KEY (ct_usage_id_id) REFERENCES ct_usage (id)');
        $this->addSql('ALTER TABLE ct_visite ADD CONSTRAINT FK_7F3E82E3E85C06CB FOREIGN KEY (ct_verificateur_id_id) REFERENCES ct_user (id)');
        $this->addSql('ALTER TABLE ct_visite ADD CONSTRAINT FK_7F3E82E3A7D01DE7 FOREIGN KEY (ct_utilisation_id_id) REFERENCES ct_utilisation (id)');
        $this->addSql('ALTER TABLE ct_visite ADD CONSTRAINT FK_7F3E82E3F18C25C4 FOREIGN KEY (ct_type_visite_id_id) REFERENCES ct_type_visite (id)');
        $this->addSql('ALTER TABLE ct_motif_tarif ADD CONSTRAINT FK_110F10F8603A0766 FOREIGN KEY (ct_motif_id_id) REFERENCES ct_motif (id)');
        $this->addSql('ALTER TABLE ct_motif_tarif ADD CONSTRAINT FK_110F10F876255A68 FOREIGN KEY (ct_arrete_prix_id) REFERENCES ct_arrete_prix (id)');
        $this->addSql('ALTER TABLE ct_visite_ct_visite_extra ADD CONSTRAINT FK_F9CF011A15D88434 FOREIGN KEY (ct_visite_extra_id) REFERENCES ct_visite_extra (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ct_visite_ct_visite_extra ADD CONSTRAINT FK_F9CF011A5314CD4 FOREIGN KEY (ct_visite_id) REFERENCES ct_visite (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ct_visite_extra_tarif ADD CONSTRAINT FK_E3F1985EB1D04D41 FOREIGN KEY (ct_imprime_tech_id_id) REFERENCES ct_imprime_tech (id)');
        $this->addSql('ALTER TABLE ct_visite_extra_tarif ADD CONSTRAINT FK_E3F1985E2BD53E47 FOREIGN KEY (ct_arrete_prix_id_id) REFERENCES ct_arrete_prix (id)');
        $this->addSql('ALTER TABLE ct_genre ADD CONSTRAINT FK_9BCBF2CE3BEDFDD8 FOREIGN KEY (ct_genre_categorie_id_id) REFERENCES ct_genre_categorie (id)');
        $this->addSql('ALTER TABLE ct_extra_vente ADD CONSTRAINT FK_C33DB5AE1D358EA FOREIGN KEY (ct_visite_id_id) REFERENCES ct_visite (id)');
        $this->addSql('ALTER TABLE ct_extra_vente ADD CONSTRAINT FK_C33DB5A92C48FC0 FOREIGN KEY (ct_visite_extra_id_id) REFERENCES ct_visite_extra (id)');
        $this->addSql('ALTER TABLE ct_carte_grise ADD CONSTRAINT FK_A447BE7336C2F638 FOREIGN KEY (ct_centre_id_id) REFERENCES ct_centre (id)');
        $this->addSql('ALTER TABLE ct_carte_grise ADD CONSTRAINT FK_A447BE73C89A4997 FOREIGN KEY (ct_carrosserie_id_id) REFERENCES ct_carrosserie (id)');
        $this->addSql('ALTER TABLE ct_carte_grise ADD CONSTRAINT FK_A447BE7311BAA3BA FOREIGN KEY (ct_zone_desserte_id_id) REFERENCES ct_zone_desserte (id)');
        $this->addSql('ALTER TABLE ct_carte_grise ADD CONSTRAINT FK_A447BE73A6F03AC4 FOREIGN KEY (ct_vehicule_id_id) REFERENCES ct_vehicule (id)');
        $this->addSql('ALTER TABLE ct_carte_grise ADD CONSTRAINT FK_A447BE73E4B6E02 FOREIGN KEY (ct_user_id_id) REFERENCES ct_user (id)');
        $this->addSql('ALTER TABLE ct_carte_grise ADD CONSTRAINT FK_A447BE73347AECB7 FOREIGN KEY (cg_antecedant_id_id) REFERENCES ct_carte_grise (id)');
        $this->addSql('ALTER TABLE ct_carte_grise ADD CONSTRAINT FK_A447BE73A7D01DE7 FOREIGN KEY (ct_utilisation_id_id) REFERENCES ct_utilisation (id)');
        $this->addSql('ALTER TABLE ct_carte_grise ADD CONSTRAINT FK_A447BE73E926E299 FOREIGN KEY (ct_source_energie_id_id) REFERENCES ct_source_energie (id)');
        $this->addSql('ALTER TABLE ct_reception ADD CONSTRAINT FK_942215A2BC603024 FOREIGN KEY (ct_genre_id_id) REFERENCES ct_genre (id)');
        $this->addSql('ALTER TABLE ct_reception ADD CONSTRAINT FK_942215A2E85C06CB FOREIGN KEY (ct_verificateur_id_id) REFERENCES ct_user (id)');
        $this->addSql('ALTER TABLE ct_reception ADD CONSTRAINT FK_942215A236C2F638 FOREIGN KEY (ct_centre_id_id) REFERENCES ct_centre (id)');
        $this->addSql('ALTER TABLE ct_reception ADD CONSTRAINT FK_942215A2A7D01DE7 FOREIGN KEY (ct_utilisation_id_id) REFERENCES ct_utilisation (id)');
        $this->addSql('ALTER TABLE ct_reception ADD CONSTRAINT FK_942215A2C89A4997 FOREIGN KEY (ct_carrosserie_id_id) REFERENCES ct_carrosserie (id)');
        $this->addSql('ALTER TABLE ct_reception ADD CONSTRAINT FK_942215A2E926E299 FOREIGN KEY (ct_source_energie_id_id) REFERENCES ct_source_energie (id)');
        $this->addSql('ALTER TABLE ct_reception ADD CONSTRAINT FK_942215A2603A0766 FOREIGN KEY (ct_motif_id_id) REFERENCES ct_motif (id)');
        $this->addSql('ALTER TABLE ct_reception ADD CONSTRAINT FK_942215A2AA1F8D61 FOREIGN KEY (ct_type_reception_id_id) REFERENCES ct_type_reception (id)');
        $this->addSql('ALTER TABLE ct_reception ADD CONSTRAINT FK_942215A2E4B6E02 FOREIGN KEY (ct_user_id_id) REFERENCES ct_user (id)');
        $this->addSql('ALTER TABLE ct_reception ADD CONSTRAINT FK_942215A2A6F03AC4 FOREIGN KEY (ct_vehicule_id_id) REFERENCES ct_vehicule (id)');
        $this->addSql('ALTER TABLE ct_proces_verbal ADD CONSTRAINT FK_556CD10D2BD53E47 FOREIGN KEY (ct_arrete_prix_id_id) REFERENCES ct_arrete_prix (id)');
        $this->addSql('ALTER TABLE ct_centre ADD CONSTRAINT FK_902E42D3E4756BB FOREIGN KEY (ct_province_id_id) REFERENCES ct_province (id)');
        $this->addSql('ALTER TABLE ct_centre ADD CONSTRAINT FK_902E42D71BF4F4B FOREIGN KEY (centre_mere_id) REFERENCES ct_centre (id)');
        $this->addSql('ALTER TABLE ct_photo ADD CONSTRAINT FK_C2C452EDBB11B80 FOREIGN KEY (ct_usage_it_id) REFERENCES ct_usage_imprime_technique (id)');
        $this->addSql('ALTER TABLE ct_historique ADD CONSTRAINT FK_7E72DEE1D2EF42B4 FOREIGN KEY (ct_historique_type_id_id) REFERENCES ct_historique_type (id)');
        $this->addSql('ALTER TABLE ct_historique ADD CONSTRAINT FK_7E72DEE1E2C56C4A FOREIGN KEY (ct_center_id_id) REFERENCES ct_centre (id)');
        $this->addSql('ALTER TABLE ct_historique ADD CONSTRAINT FK_7E72DEE1E4B6E02 FOREIGN KEY (ct_user_id_id) REFERENCES ct_user (id)');
        $this->addSql('ALTER TABLE ct_imprime_tech ADD CONSTRAINT FK_3F49AE42E4B6E02 FOREIGN KEY (ct_user_id_id) REFERENCES ct_user (id)');
        $this->addSql('ALTER TABLE ct_usage ADD CONSTRAINT FK_C8709F46EAF3885 FOREIGN KEY (ct_type_usage_id_id) REFERENCES ct_type_usage (id)');
        $this->addSql('ALTER TABLE ct_autre_vente ADD CONSTRAINT FK_BD5B077B3A162080 FOREIGN KEY (ct_autre_tarif_id_id) REFERENCES ct_autre_tarif (id)');
        $this->addSql('ALTER TABLE ct_autre_vente ADD CONSTRAINT FK_BD5B077BDBB11B80 FOREIGN KEY (ct_usage_it_id) REFERENCES ct_usage_imprime_technique (id)');
        $this->addSql('ALTER TABLE ct_autre_vente ADD CONSTRAINT FK_BD5B077B4A8E174A FOREIGN KEY (verificateur_id_id) REFERENCES ct_user (id)');
        $this->addSql('ALTER TABLE ct_autre_vente ADD CONSTRAINT FK_BD5B077BF8F2EE9 FOREIGN KEY (ct_carte_grise_id_id) REFERENCES ct_carte_grise (id)');
        $this->addSql('ALTER TABLE ct_autre_vente ADD CONSTRAINT FK_BD5B077B36C2F638 FOREIGN KEY (ct_centre_id_id) REFERENCES ct_centre (id)');
        $this->addSql('ALTER TABLE ct_autre_vente ADD CONSTRAINT FK_BD5B077B9D86650F FOREIGN KEY (user_id_id) REFERENCES ct_user (id)');
        $this->addSql('ALTER TABLE ct_bordereau ADD CONSTRAINT FK_334055ECB1D04D41 FOREIGN KEY (ct_imprime_tech_id_id) REFERENCES ct_imprime_tech (id)');
        $this->addSql('ALTER TABLE ct_bordereau ADD CONSTRAINT FK_334055ECE4B6E02 FOREIGN KEY (ct_user_id_id) REFERENCES ct_user (id)');
        $this->addSql('ALTER TABLE ct_bordereau ADD CONSTRAINT FK_334055EC36C2F638 FOREIGN KEY (ct_centre_id_id) REFERENCES ct_centre (id)');
        $this->addSql('ALTER TABLE ct_visite_ct_anomalie ADD CONSTRAINT FK_F39BC552D0C80021 FOREIGN KEY (ct_anomalie_id) REFERENCES ct_anomalie (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ct_visite_ct_anomalie ADD CONSTRAINT FK_F39BC5525314CD4 FOREIGN KEY (ct_visite_id) REFERENCES ct_visite (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ct_autre_vente_ct_visite_extra ADD CONSTRAINT FK_38C3E3BC15D88434 FOREIGN KEY (ct_visite_extra_id) REFERENCES ct_visite_extra (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ct_autre_vente_ct_visite_extra ADD CONSTRAINT FK_38C3E3BC8D1D5C87 FOREIGN KEY (ct_autre_vente_id) REFERENCES ct_autre_vente (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ct_droit_ptac ADD CONSTRAINT FK_DB918ADA2BD53E47 FOREIGN KEY (ct_arrete_prix_id_id) REFERENCES ct_arrete_prix (id)');
        $this->addSql('ALTER TABLE ct_droit_ptac ADD CONSTRAINT FK_DB918ADA3BEDFDD8 FOREIGN KEY (ct_genre_categorie_id_id) REFERENCES ct_genre_categorie (id)');
        $this->addSql('ALTER TABLE ct_droit_ptac ADD CONSTRAINT FK_DB918ADA5FFCB50 FOREIGN KEY (ct_type_droit_ptac_id_id) REFERENCES ct_type_droit_ptac (id)');
        $this->addSql('ALTER TABLE ct_autre_tarif ADD CONSTRAINT FK_3BA0A4FE32BBA609 FOREIGN KEY (ct_usage_imprime_technique_id_id) REFERENCES ct_usage_imprime_technique (id)');
        $this->addSql('ALTER TABLE ct_const_av_ded_carac ADD CONSTRAINT FK_FAC238B6BC603024 FOREIGN KEY (ct_genre_id_id) REFERENCES ct_genre (id)');
        $this->addSql('ALTER TABLE ct_const_av_ded_carac ADD CONSTRAINT FK_FAC238B6E926E299 FOREIGN KEY (ct_source_energie_id_id) REFERENCES ct_source_energie (id)');
        $this->addSql('ALTER TABLE ct_const_av_ded_carac ADD CONSTRAINT FK_FAC238B6BE9C66F4 FOREIGN KEY (ct_const_av_ded_type_id_id) REFERENCES ct_const_av_ded_type (id)');
        $this->addSql('ALTER TABLE ct_const_av_ded_carac ADD CONSTRAINT FK_FAC238B612EA7B94 FOREIGN KEY (ct_marque_id_id) REFERENCES ct_marque (id)');
        $this->addSql('ALTER TABLE ct_const_av_ded_carac ADD CONSTRAINT FK_FAC238B6C89A4997 FOREIGN KEY (ct_carrosserie_id_id) REFERENCES ct_carrosserie (id)');
        $this->addSql('DROP TABLE ct_autre_donne');
        $this->addSql('DROP TABLE ct_type_imprime');
    }
}
