# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: fr
    logo: '%kernel.project_dir%/public/image/'
    dossier_visite_premiere: '%kernel.project_dir%/public/generated/visite/premiere/'
    dossier_visite_contre: '%kernel.project_dir%/public/generated/visite/contre/'
    dossier_reception_isole: '%kernel.project_dir%/public/generated/reception/isole/'
    dossier_reception_par_type: '%kernel.project_dir%/public/generated/reception/par_type/'
    dossier_constatation: '%kernel.project_dir%/public/generated/constatation/'
    dossier_feuille_de_caisse_visite: '%kernel.project_dir%/public/generated/feuilledecaisse/visite/'
    dossier_feuille_de_caisse_reception: '%kernel.project_dir%/public/generated/feuilledecaisse/reception/'
    dossier_feuille_de_caisse_constatation: '%kernel.project_dir%/public/generated/feuilledecaisse/constatation/'
    dossier_fiche_de_controle_isole: '%kernel.project_dir%/public/generated/feuilledecaisse/isole/'
    dossier_fiche_de_controle_par_type: '%kernel.project_dir%/public/generated/feuilledecaisse/partype/'
    dossier_fiche_de_controle_constatation: '%kernel.project_dir%/public/generated/feuilledecaisse/constatation/'
    dossier_fiche_verificateur: '%kernel.project_dir%/public/generated/feuilleverificateur/'
    dossier_liste_anomalie: '%kernel.project_dir%/public/generated/listeanomalie/'
    dossier_fiche_utilisation_imprime_technique: '%kernel.project_dir%/public/generated/ficheutilisationimprimetechnique/'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
